### ISSUE TITLE
0.1.8 creates duplicate mix/solo when creating new project from template while enabled

### ISSUE THREAD

**Issue by ak5k** [ak5k/reasolobus#3]

**Comment by martman222** [comment]
I have experienced the same thing when saving a project with reasolotus enabled. Reloading the project inserts two more tracks and shifts all tracks to the right displacing record inputs and FX.

**Comment by ak5k** [comment]
> I have experienced the same thing when saving a project with reasolotus enabled. Reloading the project inserts two more tracks and shifts all tracks to the right displacing record inputs and FX.

Hi! This is a known issue. Currently, there is no reliable method for ReaSolotus to detect reloading/switching projects with already initiated mix/solo busses. When loading/switching projects, Reaper 'solo/mute button callbacks' are sent to ReaSolotus before the project has been loaded entirely, so ReaSolotus can't test via ReaScript API if the project already has Mix/Solo busses. Thus it initializes the project with new mix/solo bus.
